import { assetPath } from "../assetPath";

export const przedSwitem = {
  id: "przed-switem",
  number: "01",
  type: "Rytuał",
  title: "Przed świtem",
  time: "12 min",
  description: "Pobudka, sen i podejrzany kult wygrywania poranka.",
  byline: "ESEJ REDAKCYJNY — PELOTON",
  hero: assetPath("peloton-story-dawn.png"),
  heroWebp: "peloton-story-dawn.webp",
  heroPosition: "50% 7%",
  thumb: assetPath("peloton-story-dawn.png"),
  thumbWebp: "peloton-story-dawn.webp",
  thumbMode: "standalone",
  thumbPosition: "50% 7%",
  lead: "Pobudka o 4:42 może być wolnością. Może też być produktywnością przebraną w lycrę. Sprawdzamy, co zostaje z porannego rytuału, kiedy schowamy Stravę, ego i budzik ustawiony tylko po to, by móc o nim opowiedzieć.",
  caption: "5:18, Warszawa. Miasto jeszcze nie zaczęło dnia.",
  alt: "Kolarz w półmroku zapina buty; miniaturowa droga z pomarańczowym rowerem przecina jego kolana.",
  quote: "Pobudka nie jest medalem. Jeśli kradnie sen, cierpliwość i uwagę na drodze, poranny trening staje się bardzo elegancką formą złej decyzji.",
  quoteAfter: 2,
  editorialDebate: {
    afterSection: 4,
    kicker: "SPÓR PELOTONU · RANO",
    question: "Czy jazda o piątej rano jest wolnością — czy produktywnością w lycrze?",
    positions: [
      {
        label: "TEZA",
        title: "To jedyna godzina naprawdę własna",
        text: "Puste drogi, mniej powiadomień i trening zrobiony przed obowiązkami dają regularność, której wieczorem często nie da się już odzyskać. Dla wielu osób to nie poza, tylko jedyne realne okno na rower.",
      },
      {
        label: "KONTRA",
        title: "Niewyspanie nie jest hartem ducha",
        text: "Wczesny start nie uszlachetnia treningu. Jeżeli skraca sen, obniża koncentrację albo przerzuca koszt na rodzinę i resztę dnia, romantyczny rytuał zaczyna przypominać KPI z lampką na kierownicy.",
      },
    ],
    verdict: "Jedź rano, jeśli poranek służy życiu, a nie odwrotnie. Spokojna jazda po przespanej nocy ma sens; interwały na kredycie snu i obowiązkowy zrzut ekranu o 6:03 — znacznie mniej.",
  },
  media: [
    {
      afterSection: 1,
      src: "peloton-dawn-city-lights.png",
      webp: "peloton-dawn-city-lights.webp",
      layout: "wide",
      alt: "Samotny kolarz przejeżdża przez puste skrzyżowanie odbijające światła na mokrym asfalcie.",
      caption: "Miasto przed pierwszym tramwajem. Sygnalizacja odmienia kolory dla prawie pustych ulic.",
      credit: "ILUSTRACJA — PAPER STUDIO",
    },
    {
      afterSection: 4,
      src: "peloton-dawn-turnaround-v2.jpg",
      layout: "standard",
      alt: "Zmęczony kolarz siedzi o świcie na ławce pustego przystanku, a obok stoi jego szosowy rower.",
      caption: "Nie każdy poranek trzeba wygrać. Czasem dojrzałą decyzją treningową jest zawrócić.",
      credit: "ILUSTRACJA — PAPER STUDIO",
    },
  ],
  sources: [
    {
      label: "British Journal of Sports Medicine — konsensus o śnie sportowców",
      url: "https://pubmed.ncbi.nlm.nih.gov/33144349/",
    },
    {
      label: "British Cycling — spokojne treningi poranne i jazda na czczo",
      url: "https://www.britishcycling.org.uk/knowledge/nutrition/article/izn20150818-All-Cycling-Fasted-Morning-Rides-0",
    },
    {
      label: "Rozporządzenie Ministra Infrastruktury — obowiązkowe oświetlenie roweru",
      url: "https://api.sejm.gov.pl/eli/acts/DU/2024/502/text.pdf",
    },
  ],
  sections: [
    {
      label: "01.1",
      heading: "Wieczór przed",
      paragraphs: [
        "Alarm wibruje o 4:42. Tylko raz, bo drugi sygnał mógłby obudzić resztę domu. Przez chwilę leżę nieruchomo i próbuję sobie przypomnieć, dlaczego poprzedniego wieczoru uznałem ten plan za dobry. Za oknem nie ma jeszcze poranka. Jest matowa czerń, kilka zapalonych okien w bloku naprzeciwko i światło latarni, w którym drobny deszcz wygląda jak pył.",
        "Rower czeka przy drzwiach. Bidony są napełnione, lampki naładowane, kurtka przewieszona przez kierownicę. Wszystko zostało przygotowane wcześniej, kiedy człowiek podejmujący decyzję o pobudce wydawał się kimś innym: bardziej rozsądnym, zdyscyplinowanym i niewrażliwym na ciepło kołdry.",
        "W kuchni nie zapalam głównej lampy. Piję wodę, jem pół kromki chleba z miodem i słucham odgłosów budynku. Rury, lodówka, winda zatrzymująca się kilka pięter wyżej. O tej godzinie najgłośniejsza jest klamra kasku. Potem metaliczny klik bloków w pedałach niesie się po podwórzu z siłą, której nie ma nigdy w ciągu dnia.",
        "O 4:58 ruszam. Nie po wynik, rekord ani po piękne zdjęcie wschodu słońca. Jadę po godzinę, która nie należy jeszcze do nikogo.",
        "Poranna jazda zaczyna się poprzedniego dnia. Jeżeli o piątej trzeba szukać rękawiczek, pompować miękką oponę i czekać, aż komputer pobierze trasę, przewaga snu zwykle okazuje się zbyt duża. Dlatego mój rytuał nie zaczyna się od budzika, lecz od niewielkiego szeregu przedmiotów ułożonych wieczorem na krześle.",
        "Koszulka, spodenki, skarpetki, rękawki, cienka kamizelka. Obok kask, okulary z przezroczystymi szkłami i rękawiczki. Temperatura podawana przez aplikację jest tylko punktem wyjścia. Nad ranem otwarte pola bywają wyraźnie chłodniejsze niż centrum miasta, a wilgoć potrafi wejść pod ubranie szybciej niż zimowe powietrze. Wolę więc zabrać jedną lekką warstwę za dużo i schować ją później do kieszeni.",
        "Sprawdzam też obie lampki. Przednia ma oświetlać drogę, ale nie może świecić kierowcom prosto w oczy, dlatego jej snop kieruję lekko w dół. Tylna musi być widoczna także spod kurtki lub torby podsiodłowej. Telefon jest naładowany, trasa pobrana offline, a planowany czas powrotu wysłany jednej osobie. W kieszeni lądują dokument, mała pompka, dętka albo zestaw naprawczy, łyżka do opon i banknot. Niewiele, ale wystarczająco, by zwykłe przebicie nie zmieniło porannej jazdy w kilkukilometrowy spacer w blokach.",
        "Na pierwsze wyjazdy przed świtem warto wybierać drogi dobrze znane. Ciemność zmienia proporcje: łagodny zakręt staje się ostrzejszy, niewielka dziura pojawia się później, a znajomy las zaczyna wyglądać jak ściana. Trasa nie musi być długa. Czterdzieści lub pięćdziesiąt kilometrów przejechanych spokojnie wystarczy, żeby wrócić do domu z poczuciem odbytej podróży.",
        "Kiedy wszystko jest gotowe, poranna decyzja zostaje ograniczona do jednej czynności: wstać.",
      ],
    },
    {
      label: "01.2",
      heading: "Miasto na światłach",
      paragraphs: [
        "Pierwsze ulice wyglądają jak dekoracja zbudowana na długo przed rozpoczęciem przedstawienia. Sygnalizacja zmienia kolory dla pustych skrzyżowań. Tramwaj techniczny przesuwa się powoli po torach. Na przystanku stoi człowiek w roboczej kurtce, a pod całodobową piekarnią kierowca rozładowuje plastikowe skrzynki z chlebem.",
        "To nie jest jednak zupełnie puste miasto. Ma swoją nocną zmianę: sprzątających, ochroniarzy, kierowców autobusów, piekarzy, pracowników hal i ludzi kończących dyżur w szpitalu. Rowerzysta przecina ich poranek na chwilę, zwykle bez słów. Czasem wystarcza krótkie skinienie głowy. Ono mówi: widzę cię; wiem, że dla ciebie ten dzień zaczął się wcześniej niż dla innych.",
        "Jadę ostrożniej niż zwykle. Puste ulice zachęcają do prędkości, lecz o świcie samochody potrafią pojawiać się nagle. Kierowca może być zaspany, szyba zaparowana, a światło roweru zgubić się między latarniami. Na skrzyżowaniu szukam kontaktu wzrokowego. Nie zakładam, że pierwszeństwo zostało zauważone. Słuchawki zostają w domu; chcę słyszeć opony samochodu, szum autobusu i psa biegnącego za ogrodzeniem.",
        "Na mokrym asfalcie białe pasy połyskują jak szkło. Tory tramwajowe, studzienki i liście mają własną, zdradliwą gładkość. W dzień większość z tych szczegółów znika w ruchu i hałasie. Teraz każdy ma ostre krawędzie.",
        "Dopiero na moście miasto zaczyna się rozsuwać. Za plecami zostają biurowce, przed którymi nikt jeszcze nie zdążył zaparkować. Rzeka jest prawie czarna. Na jej powierzchni nie odbija się niebo, lecz pojedyncze lampy stojące na brzegu. Za kilkanaście minut ich światło przestanie być potrzebne, ale na razie prowadzi mnie ku rogatkom.",
      ],
    },
    {
      label: "01.3",
      heading: "Zimne kilometry",
      paragraphs: [
        "Pierwszy kwadrans nie służy do sprawdzania formy. Ciało nadal uważa, że powinno spać, a nogi poruszają się w rytmie wolniejszym od ambicji. Jadę na lekkim przełożeniu i pozwalam, by oddech sam znalazł tempo. Prędkość na ekranie nie ma znaczenia. Zimne mięśnie i sztywne barki potrzebują czasu, nie motywacyjnej przemowy.",
        "Zawsze zaczynam za mocno, jeśli w pierwszych minutach patrzę na liczby. Dlatego ekran komputera pokazuje tylko mapę i godzinę. Moc, średnia prędkość oraz segmenty mogą poczekać. Poranna jazda natychmiast karze za pośpiech: oddech staje się płytki, pot zbiera się pod kurtką, a chłód, który miał zostać na zewnątrz, wraca przy pierwszym postoju.",
        "Po dwudziestu minutach coś się zmienia. Korba zaczyna obracać się ciszej, dłonie przestają zaciskać się na kierownicy, plecy odnajdują znajome ułożenie. Światło lampy nie jest już tunelem wyciętym w ciemności. Po obu stronach pojawiają się kształty pól, ogrodzeń i drzew.",
        "Jeśli jazda ma trwać godzinę, wystarcza mi lekki posiłek przed wyjściem i bidon. Przy dłuższym wyjeździe zabieram banana, niewielką kanapkę albo prosty baton. Najważniejsze jest, żeby nie czekać na głód. O świcie łatwo pomylić pustkę w żołądku z chłodem lub sennością, a potem odkryć, że powrót prowadzi pod wiatr.",
        "Jedzenie na rowerze nie przerywa rytuału. Jest jego częścią, podobnie jak rozpięcie kamizelki na podjeździe, poprawienie lampki czy łyk wody przed wyjazdem z miasta.",
      ],
    },
    {
      label: "01.4",
      heading: "Droga bez świadków",
      paragraphs: [
        "Za ostatnim rondem kończy się chodnik, potem stacja benzynowa, magazyny i osiedle nowych domów. Droga zwęża się do dwóch pasów, między którymi biegnie wyblakła linia. Zaczynają się pola.",
        "Latem można tu poczuć zmianę temperatury niemal jak wjazd do innego pomieszczenia. Nad rowami leży wilgoć, z łąk podnosi się mgła, a zapach ziemi wypiera spaliny. Wiosną słychać ptaki, zanim da się je zobaczyć. Jesienią ciemność trwa dłużej i pierwszym znakiem dnia jest nie światło, lecz kolor: granat zastępujący czerń.",
        "Nie jadę szybko. Na tej trasie są dwa krótkie podjazdy, które w ciągu dnia zawsze prowokują do przyspieszenia. Teraz pokonuję je siedząc, równo, bez patrzenia na czas. Łańcuch przechodzi po kasecie, opona podnosi drobny piasek, gdzieś po lewej pracuje urządzenie nawadniające. To wystarcza za ścieżkę dźwiękową.",
        "Cisza o świcie nie jest brakiem odgłosów. Przeciwnie, okazuje się ich pełna. Są pojedyncze, oddalone od siebie i dlatego wyraźniejsze: zamykana brama, kogut, ciężarówka na drodze kilka kilometrów dalej, wiatr przechodzący przez topole. Własny rower również zaczyna mówić. Słychać lekko suchy łańcuch, przewód dotykający ramy, kamyk zaczepiony w bieżniku. W dzień te sygnały giną; teraz brzmią jak uwagi mechanika.",
        "Najbardziej lubię moment, kiedy gaszę przednią lampę. Nie robię tego natychmiast po pojawieniu się jasnego pasa na horyzoncie. Czekam, aż asfalt będzie wyraźny, a sylwetka roweru przestanie rzucać cień wyłącznie do tyłu. Kliknięcie przycisku jest drobnym, ale ważnym gestem. Nocny etap został zamknięty. Od tej chwili to już nie ucieczka w ciemność, lecz jazda w stronę dnia.",
      ],
    },
    {
      label: "01.5",
      heading: "Produktywność w lycrze",
      paragraphs: [
        "Rytuały bywają podejrzane. W kolarskim internecie pobudka o piątej potrafi wyglądać jak certyfikat charakteru, a człowiek śpiący do siódmej — jak projekt wymagający naprawy. Wstań wcześniej, przejedź dystans, wrzuć aktywność, popraw produktywność. Po chwili nawet cisza przed świtem ma tabelę wyników.",
        "Rachunek przychodzi później i nie ma na nim segmentów: senność o czternastej, krótsza cierpliwość, gorsza koncentracja w ruchu i domownicy, którzy również słyszeli klamrę kasku. Poranna jazda nie jest darmową godziną wyjętą z doby. Ktoś — najczęściej ten sam kolarz kilka godzin później — za nią płaci.",
        "Dlatego moja mała liturgia zawiera zasadę, której nie zapisuję w aplikacji: można zawrócić.",
        "Można skrócić trasę, jeśli chłód przenika rękawiczki. Można zatrzymać się na moście, chociaż plan treningowy nie przewiduje postoju. Można przejechać czterdzieści kilometrów zamiast sześćdziesięciu, bo na wschodzie pojawiły się ciężkie chmury. Można zostać w domu, gdy jezdnia pokrywa się lodem, widoczność znika w mgle albo organizm wyraźnie prosi o sen. Konsekwencja nie polega na ignorowaniu warunków.",
        "Dobry poranny wyjazd jest prosty. Znana trasa, sprawny rower, właściwe światło, jedna dodatkowa warstwa, jedzenie dopasowane do czasu jazdy i zapas kilkunastu minut przed obowiązkami. Ten margines jest szczególnie ważny. Pośpiech w drodze powrotnej zamienia spokojną jazdę w serię ryzykownych decyzji: zbyt szybki zakręt, przejazd na późnym żółtym, brak czasu na śniadanie.",
        "Warto mieć również krótszy wariant trasy i dwa punkty, w których można zawrócić. Prognozę najlepiej sprawdzić jeszcze raz tuż przed wyjściem, zwłaszcza kierunek wiatru i możliwość opadu. Wiatr, którego prawie nie czuć między budynkami, na otwartym polu może zdecydować o godzinie powrotu.",
        "To wszystko brzmi technicznie, ale właśnie techniczne drobiazgi pozwalają potem o nich nie myśleć. Przygotowana lampka przestaje być lampką. Staje się spokojem. Zapisana trasa przestaje być linią na ekranie. Jest zgodą na zgubienie myśli bez obawy, że zgubimy drogę.",
      ],
    },
    {
      label: "01.6",
      heading: "Punkt zwrotny",
      paragraphs: [
        "Na trzydziestym kilometrze stoi przystanek, z którego pierwszy autobus odjeżdża dopiero za godzinę. Ma ławkę, blaszany daszek i rozkład jazdy wyblakły od słońca. To mój zwyczajowy punkt zwrotny.",
        "Zatrzymuję się na kilka minut. Para unosi się znad rozpiętej kurtki, a powietrze nagle wydaje się zimniejsze niż podczas jazdy. Jem banana i piję wodę. Z oddali nadjeżdża mleczarka. Jej kierowca podnosi dłoń, jakbyśmy spotykali się tu regularnie, choć widzę go pierwszy raz.",
        "Wschód słońca rzadko przypomina ten z reklam. Niebo nie zawsze płonie pomarańczem. Częściej jasność przychodzi powoli, bez kulminacji. Szare pole robi się zielone, dach przestaje być płaską plamą, z rowu wynurza się czerwona puszka. Świat nie staje się piękniejszy. Staje się dokładniejszy.",
        "Są poranki, kiedy słońca nie widać wcale. Chmury przechodzą z granatu w jasną szarość i tylko zegarek potwierdza, że noc się skończyła. Te jazdy nie są mniej udane. Ich nagrodą nie jest widowisko, lecz przemiana: wyjechać z domu w jednym świecie i wrócić do innego.",
        "W drodze powrotnej mijam pierwsze grupki kolarzy. Jadą szybko, rozmawiają głośniej, czerwone lampki pulsują w równych odstępach. Pozdrawiamy się krótkim ruchem dłoni. Oni właśnie zaczynają. Ja mam wrażenie, że wracam z daleka, choć od domu dzieli mnie niewiele ponad dwadzieścia kilometrów.",
        "Wiatr jest teraz wyraźniejszy. Na drogach pojawiają się samochody, piekarnia otworzyła drzwi, a przed kawiarnią ktoś rozstawia krzesła. Poranny przywilej powoli wygasa.",
      ],
    },
    {
      label: "01.7",
      heading: "Zdążyć przed dniem",
      paragraphs: [
        "Do miasta wracam inną trasą, wzdłuż rzeki. Biegacze zajmują ścieżkę, pierwsze psy wyprowadzają swoich właścicieli, dostawcy blokują zatoki. Sygnalizacja, która wcześniej pracowała dla nikogo, musi teraz porządkować rosnący ruch.",
        "Na ostatnich kilometrach nie próbuję utrzymać średniej. Nogi są rozgrzane, ale uwaga zaczyna wędrować w stronę dnia: wiadomości, spotkań, zakupów, rzeczy odłożonych z wczoraj. To chwila, w której najłatwiej popełnić błąd. Dlatego zwalniam. Poranna jazda kończy się dopiero po przekroczeniu drzwi, nie po osiągnięciu zaplanowanego dystansu.",
        "Na podwórzu spotykam sąsiada wynoszącego śmieci. Patrzy na rower, potem na zegarek. „Już wracasz?” To pytanie jest częścią rytuału. Odpowiadam, że tak, chociaż przez moment mam ochotę opowiedzieć mu o pustym moście, mgle nad polami i przystanku, na którym świat odzyskał kolory. Zamiast tego wnoszę rower po schodach, zdejmuję buty i odkładam lampki do ładowania.",
        "Potem jest prysznic, duże śniadanie i kawa wypita bez pośpiechu. Mokra kurtka schnie na oparciu krzesła. Ślad błota na łydce przypomina, że wydarzyło się coś więcej niż trening.",
        "Poranna jazda nie rozwiązuje problemów. Nie czyni człowieka bardziej zdyscyplinowanym ani lepszym od tych, którzy zostali w łóżkach. Po kilku godzinach zmęczenie może wręcz wystawić rachunek za pobudkę. Jej sens jest skromniejszy.",
        "Przez chwilę żyje się w czasie pozbawionym publiczności. Nikt nie czeka na wynik. Nie trzeba się ścigać, odpowiadać ani udowadniać, że dobrze wykorzystuje się poranek. Jest tylko droga ujawniana przez lampę po kilka metrów naraz, cichy mechanizm roweru i ciało, które powoli przypomina sobie ruch.",
        "O 7:26 miasto jest już całkowicie obudzone. Autobusy stoją w korku, telefony zaczynają dzwonić, ekspresy do kawy pracują w biurach. Dla większości ludzi dzień właśnie się zaczyna.",
        "Dla mnie wydarzył się już cały mały dzień — i pozostanie niewidoczny dla wszystkich poza tymi, których przed świtem również nie było w domu.",
      ],
    },
  ],
};
