import { assetPath } from "../../assetPath";

export const przedSwitemEn = {
  id: "przed-switem",
  number: "01",
  type: "Ritual",
  title: "Before Dawn",
  time: "12 min",
  description: "Early alarms, sleep and the dubious cult of winning the morning.",
  byline: "WORDS — MAJA ROSIŃSKA / PELOTON EDITORS",
  hero: assetPath("peloton-story-dawn.png"),
  heroWebp: "peloton-story-dawn.webp",
  heroPosition: "50% 7%",
  thumb: assetPath("peloton-story-dawn.png"),
  thumbWebp: "peloton-story-dawn.webp",
  thumbMode: "standalone",
  thumbPosition: "50% 7%",
  lead: "Getting up at 4:42 can feel like freedom. It can also be productivity dressed in Lycra. We ask what remains of the morning ritual once Strava, ego and the alarm set purely for the story it tells have been put away.",
  caption: "5:18 a.m., Warsaw. The city has not yet begun its day.",
  alt: "A cyclist fastens his shoes in the half-light; a miniature road carrying an orange bicycle crosses his knees.",
  quote: "An early alarm is not a medal. If it steals sleep, patience and attention on the road, a morning ride becomes a very elegant form of bad decision.",
  quoteAfter: 2,
  editorialDebate: {
    afterSection: 4,
    kicker: "THE PELOTON DEBATE · MORNING",
    question: "Is riding at five in the morning freedom — or productivity in Lycra?",
    positions: [
      {
        label: "THE CASE FOR",
        title: "It is the only hour that is truly yours",
        text: "Empty roads, fewer notifications and a ride completed before the day's obligations create a consistency that is often impossible to recover in the evening. For many people this is not theatre, but the only genuine opening for a bike ride.",
      },
      {
        label: "THE CASE AGAINST",
        title: "Sleep deprivation is not strength of character",
        text: "An early start does not make a ride more virtuous. If it cuts sleep, dulls concentration or transfers the cost to the family and the rest of the day, the romantic ritual begins to look like a KPI with a light on the handlebars.",
      },
    ],
    verdict: "Ride early when the morning serves your life, not the other way round. An easy spin after a full night's sleep makes sense; intervals bought on sleep debt and the compulsory 6:03 screenshot make considerably less.",
  },
  media: [
    {
      afterSection: 1,
      src: "peloton-dawn-city-lights.png",
      webp: "peloton-dawn-city-lights.webp",
      layout: "wide",
      alt: "A lone cyclist crosses an empty junction, its lights reflected on wet tarmac.",
      caption: "The city before its first tram. Traffic lights change for streets that are almost empty.",
      credit: "ILLUSTRATION — PAPER STUDIO",
    },
    {
      afterSection: 4,
      src: "peloton-dawn-turnaround-v2.jpg",
      layout: "standard",
      alt: "A tired cyclist sits on the bench of an empty bus stop at dawn, his road bike beside him.",
      caption: "Not every morning has to be won. Sometimes turning back is the mature training decision.",
      credit: "ILLUSTRATION — PAPER STUDIO",
    },
  ],
  sources: [
    {
      label: "British Journal of Sports Medicine — consensus on sleep in athletes",
      url: "https://pubmed.ncbi.nlm.nih.gov/33144349/",
    },
    {
      label: "British Cycling — easy morning training and fasted rides",
      url: "https://www.britishcycling.org.uk/knowledge/nutrition/article/izn20150818-All-Cycling-Fasted-Morning-Rides-0",
    },
    {
      label: "Polish Ministry of Infrastructure regulation — mandatory bicycle lighting",
      url: "https://api.sejm.gov.pl/eli/acts/DU/2024/502/text.pdf",
    },
  ],
  sections: [
    {
      label: "01.1",
      heading: "The Night Before",
      paragraphs: [
        "The alarm vibrates at 4:42. Once only, because a second pulse might wake the rest of the house. I lie still for a moment, trying to remember why the person I was last night thought this was a good plan. There is no morning outside yet. Only a matt blackness, a few lit windows in the block opposite and a street lamp beneath which fine rain looks like dust.",
        "The bike is waiting by the door. Bottles filled, lights charged, jacket draped over the handlebars. Everything was prepared earlier, when the person deciding to wake at this hour seemed like somebody else: more sensible, more disciplined and impervious to the warmth of a duvet.",
        "I leave the main kitchen light off. I drink water, eat half a slice of bread with honey and listen to the building: pipes, refrigerator, the lift stopping several floors above. At this hour the helmet buckle is the loudest thing in the world. Then the metallic click of cleats engaging with pedals carries across the courtyard with a force it never possesses in daylight.",
        "At 4:58 I set off. Not for a result, a record or a beautiful photograph of sunrise. I am riding for an hour that does not belong to anybody yet.",
        "A morning ride begins the day before. If, at five, you still have to find your gloves, pump a soft tyre and wait for the computer to download the route, sleep usually wins. That is why my ritual begins not with the alarm, but with a small procession of objects laid out on a chair the night before.",
        "Jersey, bib shorts, socks, arm warmers, a thin gilet. Beside them: helmet, clear-lens glasses and gloves. The temperature in the app is only a starting point. Before sunrise, open fields can be markedly colder than the centre of the city, and damp can slip beneath clothing faster than winter air. I prefer to carry one light layer too many and put it in a pocket later.",
        "I check both lights as well. The front one must illuminate the road without shining directly into drivers' eyes, so I angle its beam slightly downwards. The rear must remain visible beneath a jacket or saddle bag. The phone is charged, the route downloaded for offline use and my expected return time sent to one person. My pocket receives identification, a small pump, a tube or repair kit, a tyre lever and a banknote. Not much, but enough to prevent an ordinary puncture from turning the morning ride into a walk of several kilometres in cleats.",
        "For the first rides before dawn, it is worth choosing roads you know well. Darkness changes proportions: a gentle bend becomes sharper, a small pothole appears later, a familiar forest begins to look like a wall. The route need not be long. Forty or fifty easy kilometres are enough to return home feeling that you have travelled somewhere.",
        "Once everything is ready, the morning decision is reduced to a single act: get up.",
      ],
    },
    {
      label: "01.2",
      heading: "The City Under Lights",
      paragraphs: [
        "The first streets resemble a set built long before the performance begins. Traffic lights change for empty junctions. A maintenance tram moves slowly along its rails. A man in a work jacket stands at a bus stop, while outside the twenty-four-hour bakery a driver unloads plastic crates of bread.",
        "Yet the city is not entirely empty. It has its night shift: cleaners, security guards, bus drivers, bakers, warehouse workers and people coming off duty at the hospital. A cyclist crosses their morning for a moment, usually without words. Sometimes a brief nod is enough. It says: I see you; I know your day began earlier than everyone else's.",
        "I ride more carefully than usual. Empty streets invite speed, but at dawn cars can appear suddenly. A driver may be drowsy, the windscreen misted, the bicycle light lost among the street lamps. At a junction I look for eye contact. I do not assume that my right of way has been seen. The headphones stay at home; I want to hear car tyres, the wash of a bus and a dog running behind a fence.",
        "On wet tarmac the white lines gleam like glass. Tram rails, drain covers and leaves possess their own treacherous smoothness. By day, most of these details disappear into traffic and noise. Now each has a sharp edge.",
        "Only on the bridge does the city begin to open out. Behind me are office buildings in front of which nobody has yet parked. The river is almost black. It reflects not the sky, but isolated lamps along the bank. In a dozen minutes their light will no longer be needed; for now, they guide me towards the edge of town.",
      ],
    },
    {
      label: "01.3",
      heading: "Cold Kilometres",
      paragraphs: [
        "The first quarter of an hour is no time to test your form. The body still believes it ought to be asleep, and the legs turn at a rhythm slower than ambition. I choose an easy gear and let my breathing find its own tempo. The speed on the screen is irrelevant. Cold muscles and stiff shoulders need time, not a motivational speech.",
        "I always start too hard if I look at the numbers in the opening minutes. So the computer shows only the map and the time. Power, average speed and segments can wait. A morning ride punishes haste immediately: breathing becomes shallow, sweat gathers beneath the jacket, and the cold that was meant to stay outside returns at the first stop.",
        "After twenty minutes something changes. The cranks begin to turn more quietly, my hands stop gripping the bars, my back finds its familiar position. The beam of the light is no longer a tunnel cut into darkness. The shapes of fields, fences and trees appear on either side.",
        "If the ride will last an hour, a light meal before leaving and one bottle are enough for me. For a longer outing I take a banana, a small sandwich or a simple bar. The important thing is not to wait for hunger. At dawn, an empty stomach is easily mistaken for cold or drowsiness—until you discover that the road home runs into a headwind.",
        "Eating on the bike does not interrupt the ritual. It belongs to it, just like unzipping the gilet on a climb, adjusting the light or taking a drink before leaving the city.",
      ],
    },
    {
      label: "01.4",
      heading: "A Road Without Witnesses",
      paragraphs: [
        "Beyond the final roundabout, the pavement ends; then come a petrol station, warehouses and an estate of new houses. The road narrows to two lanes divided by a faded line. The fields begin.",
        "In summer, the shift in temperature can feel almost like entering another room. Damp hangs above the ditches, mist rises from the meadows and the smell of earth displaces exhaust fumes. In spring you hear birds before you can see them. In autumn darkness lasts longer, and the first sign of day is not light but colour: navy replacing black.",
        "I am not riding fast. This route has two short climbs that always provoke an acceleration by day. Now I take them seated, evenly, without looking at the time. The chain moves across the cassette, the tyre lifts fine grit, somewhere to the left an irrigation system is working. It is enough of a soundtrack.",
        "Silence at dawn is not the absence of sound. On the contrary, it is full of it. Each sound is solitary and separated from the next, and therefore clearer: a gate closing, a cockerel, a lorry on a road several kilometres away, wind passing through poplars. Your own bicycle begins to speak as well. You hear a slightly dry chain, a cable touching the frame, a stone caught in the tread. By day these signals vanish; now they sound like a mechanic's observations.",
        "My favourite moment is when I switch off the front light. I do not do it as soon as a pale band appears on the horizon. I wait until the tarmac is distinct and the bicycle's silhouette no longer casts its shadow solely behind. The click of the button is a small but meaningful gesture. The night stage has closed. From now on, this is no longer an escape into darkness, but a ride towards the day.",
      ],
    },
    {
      label: "01.5",
      heading: "Productivity in Lycra",
      paragraphs: [
        "Rituals can be suspect. On the cycling internet, getting up at five can resemble a certificate of character, while somebody who sleeps until seven looks like a project in need of repair. Wake earlier, cover the distance, upload the ride, improve productivity. Before long, even the silence before dawn has a leaderboard.",
        "The bill arrives later and there are no segments on it: drowsiness at two in the afternoon, a shorter temper, poorer concentration in traffic, and housemates who heard the helmet buckle too. A morning ride is not a free hour extracted from the day. Somebody—usually the same cyclist a few hours later—pays for it.",
        "That is why my small liturgy contains a rule I never enter in an app: you may turn back.",
        "You may shorten the route if cold seeps through your gloves. You may stop on the bridge even though the training plan contains no pause. You may ride forty kilometres instead of sixty because heavy clouds have appeared in the east. You may stay at home when ice covers the road, visibility disappears in fog or the body is plainly asking for sleep. Consistency does not mean ignoring conditions.",
        "A good morning ride is simple. A familiar route, a sound bicycle, the right light, one extra layer, food matched to the ride and a margin of a dozen minutes before the day's obligations begin. That margin matters in particular. Hurrying home turns a quiet ride into a series of risky decisions: a corner taken too fast, crossing on a late amber, no time for breakfast.",
        "It is worth having a shorter version of the route and two points at which you can turn back. Check the forecast once more immediately before leaving, especially wind direction and the possibility of rain. A wind barely noticeable between buildings can determine your return time out in the open fields.",
        "All of this sounds technical, but technical details are precisely what allow you to stop thinking about them. A prepared light ceases to be a light. It becomes peace of mind. A saved route ceases to be a line on a screen. It is permission to lose your train of thought without fearing that you will lose the road.",
      ],
    },
    {
      label: "01.6",
      heading: "The Turning Point",
      paragraphs: [
        "At kilometre thirty stands a bus stop whose first service will not arrive for another hour. It has a bench, a sheet-metal roof and a timetable bleached by the sun. This is my usual turning point.",
        "I stop for a few minutes. Steam rises from the open jacket and the air suddenly feels colder than it did while riding. I eat a banana and drink water. A milk tanker approaches in the distance. Its driver raises a hand as though we meet here regularly, although I have never seen him before.",
        "Sunrise seldom resembles the version in advertisements. The sky does not always burn orange. More often, brightness arrives gradually, without a climax. A grey field becomes green, a roof ceases to be a flat patch, a red can emerges from a ditch. The world does not become more beautiful. It becomes more exact.",
        "There are mornings when the sun is never visible. The clouds pass from navy to pale grey and only the watch confirms that night has ended. These rides are no less successful. Their reward is not spectacle, but transformation: leaving home in one world and returning to another.",
        "On the way back I pass the first small groups of cyclists. They ride quickly, talk more loudly, their red lights pulsing at regular intervals. We greet one another with a brief movement of the hand. They are just beginning. I feel as though I am returning from far away, although little more than twenty kilometres separate me from home.",
        "The wind is more noticeable now. Cars appear on the roads, the bakery has opened its doors and somebody is setting out chairs in front of a café. The morning privilege is slowly expiring.",
      ],
    },
    {
      label: "01.7",
      heading: "Home Before the Day",
      paragraphs: [
        "I return to the city by another route, along the river. Runners occupy the path, the first dogs take their owners out, delivery vans block the bays. Traffic lights that had been working for nobody must now organise the growing flow.",
        "Over the final kilometres I make no attempt to preserve my average. The legs are warm, but attention begins to wander towards the day: messages, meetings, shopping, things left unfinished yesterday. This is the moment when a mistake is easiest to make. So I slow down. A morning ride ends only after crossing the threshold, not upon reaching the planned distance.",
        "In the courtyard I meet a neighbour taking out the rubbish. He looks at the bike, then at his watch. ‘You're back already?’ The question is part of the ritual. I say yes, although for a moment I want to tell him about the empty bridge, the mist above the fields and the bus stop where the world recovered its colours. Instead, I carry the bike upstairs, remove my shoes and put the lights on charge.",
        "Then comes a shower, a large breakfast and coffee drunk without hurry. The wet jacket dries over the back of a chair. A streak of mud on my calf is evidence that something more than training has taken place.",
        "A morning ride does not solve problems. It does not make a person more disciplined or better than those who stayed in bed. A few hours later, fatigue may even present the bill for waking so early. Its purpose is more modest.",
        "For a moment, you inhabit time without an audience. Nobody is waiting for a result. There is no need to race, reply or prove that the morning is being used well. There is only the road revealed by the light a few metres at a time, the bicycle's quiet mechanism and a body slowly remembering movement.",
        "At 7:26 the city is fully awake. Buses sit in traffic, telephones begin to ring, coffee machines work in offices. For most people, the day is just beginning.",
        "For me, an entire small day has already happened—and it will remain invisible to everyone except those who, before dawn, were not at home either.",
      ],
    },
  ],
};
