export const editorialTeamByLanguage = {
  pl: {
    kicker: "REDAKCJA / ROWKI",
    title: "Pięć uszu. Żadnego nabożeństwa.",
    intro:
      "Pięć materiałów w każdym numerze, pięć charakterów i żadnej wspólnej listy audiofilskich przykazań. Źródła są obowiązkowe; zachwyt trzeba uzasadnić.",
    affiliationLabel: "STAŁA REDAKCJA",
    magazine: "ROWKI",
    chief: {
      kicker: "REDAKTOR NACZELNY / ROWKI + PELOTON",
      title: "Wstępniak należy do naczelnego.",
      portrait: "editor-in-chief.jpg",
      portraitAlt: "Ilustracyjny portret redaktora naczelnego Rowków i Pelotonu.",
      description:
        "Redaktor naczelny wybiera temat numeru, ustawia temperaturę sporu, zamawia teksty i pisze wszystkie wstępniaki. Agenci prowadzą własne dziedziny, ale nie imitują jego głosu i nie publikują bez akceptacji.",
    },
    disclosure:
      "Portrety przedstawiają fikcyjne persony redakcyjne — wyspecjalizowane agenty pisarskie. Ich zadaniem jest rzetelny, ostry szkic; odpowiedzialność wydawnicza pozostaje po stronie redaktora naczelnego.",
    voiceLabel: "GŁOS",
    sourcesLabel: "ŹRÓDŁA",
    assignmentLabel: "W TYM NUMERZE",
    backToCover: "Wróć do okładki",
    footer: "5 AUTORÓW · 5 MATERIAŁÓW · 1 REDAKTOR NACZELNY",
    people: [
      {
        id: "jan-urbaniak", number: "01", name: "Jan Urbaniak", role: "SPRZĘT / HISTORIA",
        portrait: "editor-jan-urbaniak.jpg", portraitAlt: "Ilustracyjny portret Jana Urbaniaka, fikcyjnego redaktora sprzętowego Rowków.",
        character: "Inżynier, który nie myli metki z parametrem. Rozkręca legendy na patenty, mechanikę i warunki użytkowania.",
        voice: "Techniczny konkret, suchy dowcip i alergia na przymiotnik „audiofilski”, jeśli nie stoi za nim mechanizm albo pomiar.",
        sources: "Instrukcje, archiwa producentów, patenty i pomiary; forum jest warsztatem hipotez, nie laboratorium.",
        assignment: "„Technics: obrót doskonały”",
      },
      {
        id: "marta-sobczak", number: "02", name: "Marta Sobczak", role: "RYNEK / TŁOCZNIE",
        portrait: "editor-marta-sobczak.jpg", portraitAlt: "Ilustracyjny portret Marty Sobczak, fikcyjnej reporterki rynku muzycznego Rowków.",
        character: "Idzie za pieniędzmi, kolejką w tłoczni i odsetkiem reklamacji. Renesans winylu mierzy nie tylko sprzedażą, lecz także jakością i ceną błędu.",
        voice: "Chłodna liczba spotyka obserwację kultury. Rozcina nostalgię, ale nie szydzi z potrzeby posiadania rzeczy.",
        sources: "Raporty RIAA i IFPI, dane list sprzedaży, procesy tłoczni oraz powtarzalne sygnały społeczności.",
        assignment: "„Płyta wróciła na dobre”",
      },
      {
        id: "pawel-rzepecki", number: "03", name: "Paweł Rzepecki", role: "SŁUCHANIE / FORMA ALBUMU",
        portrait: "editor-pawel-rzepecki.jpg", portraitAlt: "Ilustracyjny portret Pawła Rzepeckiego, fikcyjnego krytyka muzycznego Rowków.",
        character: "Formalista bez cierpliwości do pustej wirtuozerii. Pyta, co dana minuta robi z napięciem albumu, a nie ilu nut wymagała.",
        voice: "Gęsty, rytmiczny esej oparty na bliskim słuchaniu. Każdy przymiotnik musi wskazać słyszalny moment.",
        sources: "Oficjalne dyskografie, wiarygodne eseje i badania muzykologiczne; pamięć fana nie zastępuje daty.",
        assignment: "„Od Pink Floyd do TesseracT”",
      },
      {
        id: "anna-krawczyk", number: "04", name: "Anna Krawczyk", role: "ARTYŚCI / SCENA",
        portrait: "editor-anna-krawczyk.jpg", portraitAlt: "Ilustracyjny portret Anny Krawczyk, fikcyjnej autorki portretów muzycznych Rowków.",
        character: "Nie pisze nekrologów na zamówienie fandomu. Bada, co w zespole było nazwą, co układem prawnym, a co realnym organizmem twórczym.",
        voice: "Twarda chronologia, uważny cytat i odważna teza wyraźnie oznaczona jako teza. Bez PR-owego znieczulenia.",
        sources: "Oświadczenia muzyków, oficjalna historia, dyskografia i datowane wywiady; status prawny nie jest metaforą.",
        assignment: "„Koniec Riverside”",
      },
      {
        id: "zofia-lewicka", number: "05", name: "Zofia Lewicka", role: "MIASTO / SKLEPY",
        portrait: "editor-zofia-lewicka.jpg", portraitAlt: "Ilustracyjny portret Zofii Lewickiej, fikcyjnej miejskiej reporterki Rowków.",
        character: "Crate-diggerka z odruchem fact-checkera. Dobry sklep poznaje po uczciwej ocenie płyty, nie po ścianie rzadkich okładek.",
        voice: "Szybki spacer, konkretna rada i detal rozmowy. Entuzjazm nie może ukryć ceny, stanu nośnika ani nieaktualnego adresu.",
        sources: "Oficjalne strony sklepów, regulaminy, weryfikacja adresów i godzin oraz forumowe tropy sprawdzone na miejscu.",
        assignment: "„Winylowa Warszawa”",
      },
    ],
  },
  en: {
    kicker: "THE EDITORS / ROWKI",
    title: "Five pairs of ears. No worship.",
    intro: "Five features per issue, five temperaments and no shared list of audiophile commandments. Sources are mandatory; delight must earn its place.",
    affiliationLabel: "PERMANENT EDITORIAL TEAM",
    magazine: "ROWKI",
    chief: {
      kicker: "EDITOR-IN-CHIEF / ROWKI + PELOTON",
      title: "The editor’s letter belongs to the editor.",
      portrait: "editor-in-chief.jpg",
      portraitAlt: "Illustrated portrait of the editor-in-chief of Rowki and Peloton.",
      description: "The editor-in-chief chooses the theme, sets the temperature of the argument, commissions the stories and writes every editor’s letter. Agents own their beats, but never imitate that voice or publish without approval.",
    },
    disclosure: "These portraits depict fictional editorial personas — specialised writing agents. Their job is a rigorous, pointed draft; publishing responsibility remains with the editor-in-chief.",
    voiceLabel: "VOICE", sourcesLabel: "SOURCES", assignmentLabel: "IN THIS ISSUE", backToCover: "Back to the cover",
    footer: "5 WRITERS · 5 FEATURES · 1 EDITOR-IN-CHIEF",
    people: [
      {
        id: "jan-urbaniak", number: "01", name: "Jan Urbaniak", role: "EQUIPMENT / HISTORY",
        portrait: "editor-jan-urbaniak.jpg", portraitAlt: "Illustrated portrait of Jan Urbaniak, a fictional Rowki equipment editor.",
        character: "An engineer who never mistakes a price tag for a parameter. He strips legends down to patents, mechanics and use conditions.",
        voice: "Technical detail, dry wit and an allergy to “audiophile” when no mechanism or measurement follows.",
        sources: "Manuals, manufacturer archives, patents and measurements; a forum is a workshop for hypotheses, not a laboratory.",
        assignment: "“Technics: the perfect rotation”",
      },
      {
        id: "marta-sobczak", number: "02", name: "Marta Sobczak", role: "MARKET / PRESSING PLANTS",
        portrait: "editor-marta-sobczak.jpg", portraitAlt: "Illustrated portrait of Marta Sobczak, a fictional Rowki music-market reporter.",
        character: "She follows the money, the pressing queue and the return rate. The vinyl revival is measured in quality and failure cost as well as sales.",
        voice: "A cool number meets cultural observation. She cuts through nostalgia without mocking the need to own a physical object.",
        sources: "RIAA and IFPI reports, chart data, pressing-plant processes and recurring community signals.",
        assignment: "“Vinyl is back for good”",
      },
      {
        id: "pawel-rzepecki", number: "03", name: "Paweł Rzepecki", role: "LISTENING / ALBUM FORM",
        portrait: "editor-pawel-rzepecki.jpg", portraitAlt: "Illustrated portrait of Paweł Rzepecki, a fictional Rowki music critic.",
        character: "A formalist with no patience for empty virtuosity. He asks what a minute does to the album’s tension, not how many notes it required.",
        voice: "A dense, rhythmic essay grounded in close listening. Every adjective must point to an audible moment.",
        sources: "Official discographies, reliable essays and musicology; fan memory never replaces a date.",
        assignment: "“From Pink Floyd to TesseracT”",
      },
      {
        id: "anna-krawczyk", number: "04", name: "Anna Krawczyk", role: "ARTISTS / SCENE",
        portrait: "editor-anna-krawczyk.jpg", portraitAlt: "Illustrated portrait of Anna Krawczyk, a fictional Rowki music-profile writer.",
        character: "She does not write obituaries to order for a fandom. She asks what in a band was a name, a legal arrangement or a living creative organism.",
        voice: "Hard chronology, careful quotation and a bold thesis clearly marked as thesis. No PR anaesthetic.",
        sources: "Musicians’ statements, official history, discography and dated interviews; legal status is not a metaphor.",
        assignment: "“The end of Riverside”",
      },
      {
        id: "zofia-lewicka", number: "05", name: "Zofia Lewicka", role: "CITY / RECORD SHOPS",
        portrait: "editor-zofia-lewicka.jpg", portraitAlt: "Illustrated portrait of Zofia Lewicka, a fictional Rowki city reporter.",
        character: "A crate digger with a fact-checker’s reflex. A good shop is defined by honest grading, not a wall of rare sleeves.",
        voice: "A brisk walk, practical advice and one telling conversational detail. Enthusiasm may not hide price, condition or an outdated address.",
        sources: "Official shop pages, terms, current address and hours verification, plus forum leads checked on the ground.",
        assignment: "“Vinyl Warsaw”",
      },
    ],
  },
};
